### ISSUE TITLE
Issue with scoring

### ISSUE THREAD

**Issue by aeturch** [Front-Row-Coders/SuperTicTacToe#21]
I believe the scoring function is incorrect.
![screen shot 2015-04-28 at 9 47 55 am](https://cloud.githubusercontent.com/assets/5882640/7372337/d3b622f8-ed8b-11e4-9dc1-17829614841f.png)
In the above screenshot, when AI completed the 6-in-a-row, it was only given 2 points (should be 3). It also was not given a point for the diagonal 4-in-a-row.
![screen shot 2015-04-28 at 10 05 17 am](https://cloud.githubusercontent.com/assets/5882640/7372766/36510976-ed8e-11e4-88dd-e128f0526958.png)
In this screenshot, Player and AI should both have 3 points.

**Comment by generalnova** [comment]
Scoring has been properly corrected.
