### ISSUE TITLE
Turn indicator when AI goes first

### ISSUE THREAD

**Issue by aeturch** [Front-Row-Coders/SuperTicTacToe#22]
In Single Player mode, if the option is checked for AI to go first, the AI makes the move but the turn indicator does not switch back to blue for the user.
![screen shot 2015-04-28 at 5 13 49 pm](https://cloud.githubusercontent.com/assets/5882640/7381544/011d674a-edca-11e4-96a0-a9a7e6032651.png)

**Comment by generalnova** [comment]
Fixed with the latest commit. Changed the turn changing (toggling) to a method implementation.
