### ISSUE TITLE
Scoring (again)

### ISSUE THREAD

**Issue by aeturch** [Front-Row-Coders/SuperTicTacToe#26]
I played several games and the scoring worked fine up until the below:
![screen shot 2015-04-29 at 8 22 43 am](https://cloud.githubusercontent.com/assets/5882640/7391847/8b65b8f6-ee49-11e4-9fbd-d528b6d27872.png)
I should have two points. I recreated the board (with a different stone placement order) in multiplayer mode and got the correct result of two points:
![screen shot 2015-04-29 at 8 25 45 am](https://cloud.githubusercontent.com/assets/5882640/7391881/ae10cf4e-ee49-11e4-859d-de03b7681785.png)

EDIT:
![screen shot 2015-04-29 at 8 36 48 am](https://cloud.githubusercontent.com/assets/5882640/7392094/18be612a-ee4b-11e4-81d1-a554656f684d.png)
When I placed the circled stone, I should have been awarded two points, because I completed a 5-in-a-row. I only gained one point.

![screen shot 2015-04-29 at 8 40 57 am](https://cloud.githubusercontent.com/assets/5882640/7392167/98a64cb8-ee4b-11e4-8278-0e4ea753038b.png)
The circled stone completed a 4-in-a-row AND extended a 4-in-a-row to a 5-in-a-row, so should have resulted in two points. I gained one.

**Comment by generalnova** [comment]
Fixed this issue by saving the direction of the counted in-a-rows.
